# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 274d51c7a20c0a4a627d65623bb288d9ad9d64318143f07923743d8189825c2d5888b825bfbf8298fdddb5bc51cffdce7669bb26d91e756d701930cd09abc9b4

test:
  secret_key_base: 7a5c829902df8bbce4bd836e69d6b2aa33a659fd40dee0c1b633bd3244456d57c7f02364b729c69d788c8ea32f6ec71653f44232cff429de77ef403be0162f4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
